-- Create table for learned attack patterns
CREATE TABLE public.learned_attack_patterns (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  organization_id UUID REFERENCES public.organizations(id),
  pattern_name TEXT NOT NULL,
  attack_type TEXT NOT NULL,
  indicators JSONB NOT NULL DEFAULT '[]'::jsonb,
  detection_rules JSONB NOT NULL DEFAULT '[]'::jsonb,
  countermeasures JSONB NOT NULL DEFAULT '[]'::jsonb,
  confidence_score NUMERIC DEFAULT 0,
  times_detected INTEGER DEFAULT 1,
  first_seen_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  last_seen_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  is_active BOOLEAN DEFAULT true,
  learned_from_incidents TEXT[] DEFAULT '{}',
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Create table for adaptive defense rules generated by AI
CREATE TABLE public.adaptive_defense_rules (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  organization_id UUID REFERENCES public.organizations(id),
  rule_name TEXT NOT NULL,
  rule_type TEXT NOT NULL,
  description TEXT,
  trigger_conditions JSONB NOT NULL DEFAULT '{}'::jsonb,
  actions JSONB NOT NULL DEFAULT '[]'::jsonb,
  priority INTEGER DEFAULT 50,
  is_enabled BOOLEAN DEFAULT true,
  is_auto_generated BOOLEAN DEFAULT true,
  effectiveness_score NUMERIC DEFAULT 0,
  times_triggered INTEGER DEFAULT 0,
  last_triggered_at TIMESTAMP WITH TIME ZONE,
  source_pattern_id UUID REFERENCES public.learned_attack_patterns(id),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Create table to track learning events and adaptations
CREATE TABLE public.defense_learning_events (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  organization_id UUID REFERENCES public.organizations(id),
  event_type TEXT NOT NULL,
  source_data JSONB NOT NULL DEFAULT '{}'::jsonb,
  analysis_result JSONB,
  patterns_identified INTEGER DEFAULT 0,
  rules_generated INTEGER DEFAULT 0,
  rules_updated INTEGER DEFAULT 0,
  processing_time_ms INTEGER,
  status TEXT DEFAULT 'pending',
  error_message TEXT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.learned_attack_patterns ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.adaptive_defense_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.defense_learning_events ENABLE ROW LEVEL SECURITY;

-- RLS Policies for learned_attack_patterns
CREATE POLICY "Security analysts can view attack patterns"
  ON public.learned_attack_patterns FOR SELECT
  USING (auth.uid() IS NOT NULL);

CREATE POLICY "Security analysts can manage attack patterns"
  ON public.learned_attack_patterns FOR ALL
  USING (get_user_role() = ANY (ARRAY['admin'::user_role, 'security_analyst'::user_role]));

-- RLS Policies for adaptive_defense_rules
CREATE POLICY "Security analysts can view defense rules"
  ON public.adaptive_defense_rules FOR SELECT
  USING (auth.uid() IS NOT NULL);

CREATE POLICY "Security analysts can manage defense rules"
  ON public.adaptive_defense_rules FOR ALL
  USING (get_user_role() = ANY (ARRAY['admin'::user_role, 'security_analyst'::user_role]));

-- RLS Policies for defense_learning_events
CREATE POLICY "Security analysts can view learning events"
  ON public.defense_learning_events FOR SELECT
  USING (auth.uid() IS NOT NULL);

CREATE POLICY "System can create learning events"
  ON public.defense_learning_events FOR INSERT
  WITH CHECK (auth.uid() IS NOT NULL);

-- Add updated_at triggers
CREATE TRIGGER update_learned_attack_patterns_updated_at
  BEFORE UPDATE ON public.learned_attack_patterns
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_adaptive_defense_rules_updated_at
  BEFORE UPDATE ON public.adaptive_defense_rules
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();